# Generated by Django 6.0 on 2026-01-19 01:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novae_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('grade_level', models.CharField(choices=[('K', 'Kindergarten'), ('1st', '1st Grade'), ('2nd', '2nd Grade'), ('3rd', '3rd Grade'), ('4th', '4th Grade'), ('5th', '5th Grade'), ('6th', '6th Grade'), ('7th', '7th Grade'), ('8th', '8th Grade'), ('9th', '9th Grade'), ('10th', '10th Grade'), ('11th', '11th Grade'), ('12th', '12th Grade')], max_length=4)),
                ('is_demo', models.BooleanField(default=False, help_text='Demo courses are accessible without payment.')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_text_answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('K', 'Kindergarten'), ('1st', '1st Grade'), ('2nd', '2nd Grade'), ('3rd', '3rd Grade'), ('4th', '4th Grade'), ('5th', '5th Grade'), ('6th', '6th Grade'), ('7th', '7th Grade'), ('8th', '8th Grade'), ('9th', '9th Grade'), ('10th', '10th Grade'), ('11th', '11th Grade'), ('12th', '12th Grade')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='daily_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='last_active_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='novae_app.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_sample', models.BooleanField(default=False, help_text='Sample lessons are accessible in demo mode.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='novae_app.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
